/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GeminiProTestRouteImport } from './routes/gemini-pro-test'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AuthGoogleRouteImport } from './routes/auth/google'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiHeroPhotoRouteImport } from './routes/api/hero-photo'
import { Route as ApiGenerateItineraryRouteImport } from './routes/api/generate-itinerary'
import { Route as ApiEnrichPlanPhotosRouteImport } from './routes/api/enrich-plan-photos'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedMyTripsRouteImport } from './routes/_authenticated.my-trips'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as ApiSearchStatusRouteImport } from './routes/api/search/status'
import { Route as ApiAuthGoogleStartRouteImport } from './routes/api/auth/google-start'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedMyTripsPlanIdRouteImport } from './routes/_authenticated.my-trips.$planId'
import { Route as AuthenticatedAdminWebhooksRouteImport } from './routes/_authenticated.admin.webhooks'
import { Route as AuthenticatedAdminPdfDownloadsRouteImport } from './routes/_authenticated.admin.pdf-downloads'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GeminiProTestRoute = GeminiProTestRouteImport.update({
  id: '/gemini-pro-test',
  path: '/gemini-pro-test',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleRoute = AuthGoogleRouteImport.update({
  id: '/auth/google',
  path: '/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHeroPhotoRoute = ApiHeroPhotoRouteImport.update({
  id: '/api/hero-photo',
  path: '/api/hero-photo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateItineraryRoute = ApiGenerateItineraryRouteImport.update({
  id: '/api/generate-itinerary',
  path: '/api/generate-itinerary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEnrichPlanPhotosRoute = ApiEnrichPlanPhotosRouteImport.update({
  id: '/api/enrich-plan-photos',
  path: '/api/enrich-plan-photos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyTripsRoute = AuthenticatedMyTripsRouteImport.update({
  id: '/my-trips',
  path: '/my-trips',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiSearchStatusRoute = ApiSearchStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApiSearchRoute,
} as any)
const ApiAuthGoogleStartRoute = ApiAuthGoogleStartRouteImport.update({
  id: '/api/auth/google-start',
  path: '/api/auth/google-start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMyTripsPlanIdRoute =
  AuthenticatedMyTripsPlanIdRouteImport.update({
    id: '/$planId',
    path: '/$planId',
    getParentRoute: () => AuthenticatedMyTripsRoute,
  } as any)
const AuthenticatedAdminWebhooksRoute =
  AuthenticatedAdminWebhooksRouteImport.update({
    id: '/admin/webhooks',
    path: '/admin/webhooks',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPdfDownloadsRoute =
  AuthenticatedAdminPdfDownloadsRouteImport.update({
    id: '/admin/pdf-downloads',
    path: '/admin/pdf-downloads',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gemini-pro-test': typeof GeminiProTestRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/my-trips': typeof AuthenticatedMyTripsRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/api/enrich-plan-photos': typeof ApiEnrichPlanPhotosRoute
  '/api/generate-itinerary': typeof ApiGenerateItineraryRoute
  '/api/hero-photo': typeof ApiHeroPhotoRoute
  '/api/search': typeof ApiSearchRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/google': typeof AuthGoogleRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/admin/pdf-downloads': typeof AuthenticatedAdminPdfDownloadsRoute
  '/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/my-trips/$planId': typeof AuthenticatedMyTripsPlanIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/google-start': typeof ApiAuthGoogleStartRoute
  '/api/search/status': typeof ApiSearchStatusRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gemini-pro-test': typeof GeminiProTestRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/my-trips': typeof AuthenticatedMyTripsRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/api/enrich-plan-photos': typeof ApiEnrichPlanPhotosRoute
  '/api/generate-itinerary': typeof ApiGenerateItineraryRoute
  '/api/hero-photo': typeof ApiHeroPhotoRoute
  '/api/search': typeof ApiSearchRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/google': typeof AuthGoogleRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/admin/pdf-downloads': typeof AuthenticatedAdminPdfDownloadsRoute
  '/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/my-trips/$planId': typeof AuthenticatedMyTripsPlanIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/google-start': typeof ApiAuthGoogleStartRoute
  '/api/search/status': typeof ApiSearchStatusRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/gemini-pro-test': typeof GeminiProTestRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/my-trips': typeof AuthenticatedMyTripsRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/api/enrich-plan-photos': typeof ApiEnrichPlanPhotosRoute
  '/api/generate-itinerary': typeof ApiGenerateItineraryRoute
  '/api/hero-photo': typeof ApiHeroPhotoRoute
  '/api/search': typeof ApiSearchRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/google': typeof AuthGoogleRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/_authenticated/admin/pdf-downloads': typeof AuthenticatedAdminPdfDownloadsRoute
  '/_authenticated/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/_authenticated/my-trips/$planId': typeof AuthenticatedMyTripsPlanIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/google-start': typeof ApiAuthGoogleStartRoute
  '/api/search/status': typeof ApiSearchStatusRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/gemini-pro-test'
    | '/login'
    | '/privacy'
    | '/refunds'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/dashboard'
    | '/my-trips'
    | '/profile'
    | '/api/enrich-plan-photos'
    | '/api/generate-itinerary'
    | '/api/hero-photo'
    | '/api/search'
    | '/auth/callback'
    | '/auth/google'
    | '/checkout/return'
    | '/admin/pdf-downloads'
    | '/admin/webhooks'
    | '/my-trips/$planId'
    | '/api/auth/$'
    | '/api/auth/google-start'
    | '/api/search/status'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/gemini-pro-test'
    | '/login'
    | '/privacy'
    | '/refunds'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/dashboard'
    | '/my-trips'
    | '/profile'
    | '/api/enrich-plan-photos'
    | '/api/generate-itinerary'
    | '/api/hero-photo'
    | '/api/search'
    | '/auth/callback'
    | '/auth/google'
    | '/checkout/return'
    | '/admin/pdf-downloads'
    | '/admin/webhooks'
    | '/my-trips/$planId'
    | '/api/auth/$'
    | '/api/auth/google-start'
    | '/api/search/status'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/gemini-pro-test'
    | '/login'
    | '/privacy'
    | '/refunds'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/_authenticated/dashboard'
    | '/_authenticated/my-trips'
    | '/_authenticated/profile'
    | '/api/enrich-plan-photos'
    | '/api/generate-itinerary'
    | '/api/hero-photo'
    | '/api/search'
    | '/auth/callback'
    | '/auth/google'
    | '/checkout/return'
    | '/_authenticated/admin/pdf-downloads'
    | '/_authenticated/admin/webhooks'
    | '/_authenticated/my-trips/$planId'
    | '/api/auth/$'
    | '/api/auth/google-start'
    | '/api/search/status'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  GeminiProTestRoute: typeof GeminiProTestRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundsRoute: typeof RefundsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  ApiEnrichPlanPhotosRoute: typeof ApiEnrichPlanPhotosRoute
  ApiGenerateItineraryRoute: typeof ApiGenerateItineraryRoute
  ApiHeroPhotoRoute: typeof ApiHeroPhotoRoute
  ApiSearchRoute: typeof ApiSearchRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthGoogleRoute: typeof AuthGoogleRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthGoogleStartRoute: typeof ApiAuthGoogleStartRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gemini-pro-test': {
      id: '/gemini-pro-test'
      path: '/gemini-pro-test'
      fullPath: '/gemini-pro-test'
      preLoaderRoute: typeof GeminiProTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google': {
      id: '/auth/google'
      path: '/auth/google'
      fullPath: '/auth/google'
      preLoaderRoute: typeof AuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hero-photo': {
      id: '/api/hero-photo'
      path: '/api/hero-photo'
      fullPath: '/api/hero-photo'
      preLoaderRoute: typeof ApiHeroPhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-itinerary': {
      id: '/api/generate-itinerary'
      path: '/api/generate-itinerary'
      fullPath: '/api/generate-itinerary'
      preLoaderRoute: typeof ApiGenerateItineraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/enrich-plan-photos': {
      id: '/api/enrich-plan-photos'
      path: '/api/enrich-plan-photos'
      fullPath: '/api/enrich-plan-photos'
      preLoaderRoute: typeof ApiEnrichPlanPhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-trips': {
      id: '/_authenticated/my-trips'
      path: '/my-trips'
      fullPath: '/my-trips'
      preLoaderRoute: typeof AuthenticatedMyTripsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/search/status': {
      id: '/api/search/status'
      path: '/status'
      fullPath: '/api/search/status'
      preLoaderRoute: typeof ApiSearchStatusRouteImport
      parentRoute: typeof ApiSearchRoute
    }
    '/api/auth/google-start': {
      id: '/api/auth/google-start'
      path: '/api/auth/google-start'
      fullPath: '/api/auth/google-start'
      preLoaderRoute: typeof ApiAuthGoogleStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/my-trips/$planId': {
      id: '/_authenticated/my-trips/$planId'
      path: '/$planId'
      fullPath: '/my-trips/$planId'
      preLoaderRoute: typeof AuthenticatedMyTripsPlanIdRouteImport
      parentRoute: typeof AuthenticatedMyTripsRoute
    }
    '/_authenticated/admin/webhooks': {
      id: '/_authenticated/admin/webhooks'
      path: '/admin/webhooks'
      fullPath: '/admin/webhooks'
      preLoaderRoute: typeof AuthenticatedAdminWebhooksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/pdf-downloads': {
      id: '/_authenticated/admin/pdf-downloads'
      path: '/admin/pdf-downloads'
      fullPath: '/admin/pdf-downloads'
      preLoaderRoute: typeof AuthenticatedAdminPdfDownloadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedMyTripsRouteChildren {
  AuthenticatedMyTripsPlanIdRoute: typeof AuthenticatedMyTripsPlanIdRoute
}

const AuthenticatedMyTripsRouteChildren: AuthenticatedMyTripsRouteChildren = {
  AuthenticatedMyTripsPlanIdRoute: AuthenticatedMyTripsPlanIdRoute,
}

const AuthenticatedMyTripsRouteWithChildren =
  AuthenticatedMyTripsRoute._addFileChildren(AuthenticatedMyTripsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMyTripsRoute: typeof AuthenticatedMyTripsRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedAdminPdfDownloadsRoute: typeof AuthenticatedAdminPdfDownloadsRoute
  AuthenticatedAdminWebhooksRoute: typeof AuthenticatedAdminWebhooksRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMyTripsRoute: AuthenticatedMyTripsRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedAdminPdfDownloadsRoute: AuthenticatedAdminPdfDownloadsRoute,
  AuthenticatedAdminWebhooksRoute: AuthenticatedAdminWebhooksRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiSearchRouteChildren {
  ApiSearchStatusRoute: typeof ApiSearchStatusRoute
}

const ApiSearchRouteChildren: ApiSearchRouteChildren = {
  ApiSearchStatusRoute: ApiSearchStatusRoute,
}

const ApiSearchRouteWithChildren = ApiSearchRoute._addFileChildren(
  ApiSearchRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  GeminiProTestRoute: GeminiProTestRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RefundsRoute: RefundsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  ApiEnrichPlanPhotosRoute: ApiEnrichPlanPhotosRoute,
  ApiGenerateItineraryRoute: ApiGenerateItineraryRoute,
  ApiHeroPhotoRoute: ApiHeroPhotoRoute,
  ApiSearchRoute: ApiSearchRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthGoogleRoute: AuthGoogleRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthGoogleStartRoute: ApiAuthGoogleStartRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
